# Configuration file for LLVM IR Transformer
# Maps array references to capability indices


["%input"]
"cap" = 0
"device" = "local"
"size" = 16206

["%xinput"]
"cap" = 1
"device" = "host"
"size" = 16206

["%xpattern"]
"cap" = 2
"device" = "host"
"size" = 4
"omit_array" = true

["%xkmpNext"]
"cap" = 3
"device" = "host"
"size" = 4
"omit_array" = true

["%xn_matches"]
"cap" = 4
"device" = "host"
"size" = 1
"omit_array" = true

["%kmpNext"]
"cap" = 5
"device" = "local"
"size" = 4
"omit_array" = true

["%n_matches"]
"cap" = 6
"device" = "local"
"size" = 1
"omit_array" = true

["%pattern"]
"cap" = 7
"device" = "local"
"size" = 4
"omit_array" = true
