/*
Implementation based on http://www-igm.univ-mlv.fr/~lecroq/string/node8.html
*/

#define PATTERN_SIZE 4
#define STRING_SIZE (16206)

void CPF(int pattern[PATTERN_SIZE], int kmpNext[PATTERN_SIZE]) {
  int k, q;
  k = 0;
  kmpNext[0] = 0;

c1:
  for (q = 1; q < PATTERN_SIZE; q++) {
  c2:
    while (k > 0 && pattern[k] != pattern[q]) {
      k = kmpNext[q];
    }
    if (pattern[k] == pattern[q]) {
      k++;
    }
    kmpNext[q] = k;
  }
}

void hls_top(int size, int xpattern[PATTERN_SIZE], int xinput[STRING_SIZE],
             int xkmpNext[PATTERN_SIZE], int xn_matches[1]) {
#pragma HLS INTERFACE m_axi port = xpattern
#pragma HLS INTERFACE m_axi port = xinput
#pragma HLS INTERFACE m_axi port = xkmpNext
#pragma HLS INTERFACE m_axi port = xn_matches
#pragma HLS INTERFACE s_axilite port = size
#pragma HLS INTERFACE s_axilite port = return
  int i, q;

  int pattern[PATTERN_SIZE];
  int input[STRING_SIZE];
  int kmpNext[PATTERN_SIZE];
  int n_matches[1];

  for (i = 0; i < PATTERN_SIZE; i++)
    pattern[i] = xpattern[i];
  for (i = 0; i < PATTERN_SIZE; i++)
    kmpNext[i] = xkmpNext[i];
  for (i = 0; i < size; i++)
    input[i] = xinput[i];

  n_matches[0] = 0;

  CPF(pattern, kmpNext);

  q = 0;
k1:
  for (i = 0; i < size; i++) {
  k2:
    while (q > 0 && pattern[q] != input[i]) {
      q = kmpNext[q];
    }
    if (pattern[q] == input[i]) {
      q++;
    }
    if (q >= PATTERN_SIZE) {
      n_matches[0] = n_matches[0] + 1;
      q = kmpNext[q - 1];
    }
  }

  xn_matches[0] = n_matches[0];
}

int main() {
  char pattern[PATTERN_SIZE] = "bull";
  char input[16206] =
      "TRwasshotinanassassinationattemptbyJohnSchrankwhohadbeenhavingdisturbing"
      "dreamsaboutTRspredecessorWilliamMcKinleyandalsothoughtthatnopresidentsho"
      "uldservemorethantwotermsSchrankspenttherestofhislifeinamentalinstitution"
      "NoonecametovisithimHediedshortlyafterFranklinDelanoRooseveltTRsfifthcous"
      "inwaselectedtoathirdtermSchrankhadstalkedTRforthousandsofmilesbeforegett"
      "ingaclearshotathiminMilwaukeeSchrankwascaughtonthespotFriendsIshallaskyo"
      "utobeasquietaspossibleIdontknowwhetheryoufullyunderstandthatIhavejustbee"
      "nshotbutittakesmorethanthattokillaBullMooseButfortunatelyIhadmymanuscrip"
      "tsoyouseeIwasgoingtomakealongspeechandthereisabulletthereiswherethebulle"
      "twentthroughanditprobablysavedmefromitgoingintomyheartThebulletisinmenow"
      "sothatIcannotmakeaverylongspeechbutIwilltrymybestAndnowfriendsIwanttotak"
      "eadvantageofthisincidenttosayawordofsolemnwarningtomyfellowcountrymenFir"
      "stofallIwanttosaythisaboutmyselfIhavealtogethertooimportantthingstothink"
      "oftofeelanyconcernovermyowndeathandnowIcannotspeaktoyouinsincerelywithin"
      "fiveminutesofbeingshotIamtellingyoutheliteraltruthwhenIsaythatmyconcerni"
      "sformanyotherthingsItisnotintheleastformyownlifeIwantyoutounderstandthat"
      "IamaheadofthegameanywayNomanhashadahappierlifethanIhaveledahappierlifein"
      "everywayIhavebeenabletodocertainthingsthatIgreatlywishedtodoandIamintere"
      "stedindoingotherthingsIcantellyouwithabsolutetruthfulnessthatIamverymuch"
      "uninterestedinwhetherIamshotornotItwasjustaswhenIwascolonelofmyregimentI"
      "alwaysfeltthataprivatewastobeexcusedforfeelingattimessomepangsofanxietya"
      "bouthispersonalsafetybutIcannotunderstandamanfittobeacolonelwhocanpayany"
      "heedtohispersonalsafetywhenheisoccupiedasheoughttobewiththeabsorbingdesi"
      "retodohisdutyIaminthiscausewithmywholeheartandsoulIbelievethattheProgres"
      "sivemovementismakinglifealittleeasierforallourpeopleamovementtotrytotake"
      "theburdensoffthemenandespeciallythewomenandchildrenofthiscountryIamabsor"
      "bedinthesuccessofthatmovementFriendsIaskyounowthiseveningtoacceptwhatIam"
      "sayingasabsolutelytruewhenItellyouIamnotthinkingofmyownsuccessIamnotthin"
      "kingofmylifeorofanythingconnectedwithmepersonallyIamthinkingofthemovemen"
      "tIsaythisbywayofintroductionbecauseIwanttosaysomethingveryserioustoourpe"
      "opleandespeciallytothenewspapersIdontknowanythingaboutwhothemanwaswhosho"
      "tmetonightHewasseizedatoncebyoneofthestenographersinmypartyMrMartinandIs"
      "upposeisnowinthehandsofthepoliceHeshottokillHeshottheshotthebulletwentin"
      "hereIwillshowyouIamgoingtoaskyoutobeasquietaspossibleforIamnotabletogive"
      "tochallengeofthebullmoosequiteasloudlyNowIdonotknowwhohewasorwhatherepre"
      "sentedHewasacowardHestoodinthedarknessinthecrowdaroundtheautomobileandwh"
      "entheycheeredmeandIgotuptobowhesteppedforwardandshotmeinthedarknessNowfr"
      "iendsofcourseIdonotknowasIsayanythingabouthimbutitisaverynaturalthingtha"
      "tweakandviciousmindsshouldbeinflamedtoactsofviolencebythekindofawfulmend"
      "acityandabusethathavebeenheapeduponmeforthelastthreemonthsbythepapersint"
      "heinterestofnotonlyMrDebsbutofMrWilsonandMrTaftFriendsIwilldisownandrepu"
      "diateanymanofmypartywhoattackswithsuchfoulslanderandabuseanyopponentofan"
      "yotherpartyandnowIwishtosayseriouslytoallthedailynewspaperstotheRepublic"
      "anstheDemocratandSocialistpartiesthattheycannotmonthinmonthoutandyearina"
      "ndyearoutmakethekindofuntruthfulofbitterassaultthattheyhavemadeandnotexp"
      "ectthatbrutalviolentnaturesorbrutalandviolentcharactersespeciallywhenthe"
      "brutalityisaccompaniedbyanotverystrongmindtheycannotexpectthatsuchnature"
      "swillbeunaffectedbyitNowfriendsIamnotspeakingformyselfatallIgiveyoumywor"
      "dIdonotcarearapaboutbeingshotnotarapIhavehadagoodmanyexperiencesinmytime"
      "andthisisoneofthemWhatIcareforismycountryIwishIwereabletoimpressuponmype"
      "opleourpeoplethedutytofeelstronglybuttospeakthetruthoftheiropponentsIsay"
      "nowIhaveneversaidonewordonethestumpagainstanyopponentthatIcannotdefendIh"
      "avesaidnothingthatIcouldnotsubstantiateandnothingthatIoughtnottohavesaid"
      "nothingthatInothingthatlookingbackatIwouldnotsayagainNowfriendsitoughtno"
      "ttobetoomuchtoaskthatouropponents[speakingtosomeoneonthestage]"
      "IamnotsickatallIamallrightIcannottellyouofwhatinfinitesimalimportanceIre"
      "gardthisincidentascomparedwiththegreatissuesatstakeinthiscampaignandIask"
      "itnotformysakenottheleastintheworldbutforthesakeofcommoncountrythattheym"
      "akeuptheirmindstospeakonlythetruthandnotusethatkindofslanderandmendacity"
      "whichiftakenseriouslymustinciteweakandviolentnaturestocrimesofviolenceDo"
      "ntyoumakeanymistakeDontyoupitymeIamallrightIamallrightandyoucannotescape"
      "listeningtothespeecheitherAndnowfriendsthisincidentthathasjustoccurredth"
      "isefforttoassassinatemeemphasizestoapeculiardegreetheneedoftheProgressiv"
      "emovementFriendseverygoodcitizenoughttodoeverythinginhisorherpowertoprev"
      "entthecomingofthedaywhenweshallseeinthiscountrytworecognizedcreedsfighti"
      "ngoneanotherwhenweshallseethecreedoftheHavenotsarraignedagainstthecreedo"
      "ftheHavesWhenthatdaycomesthensuchincidentsasthistonightwillbecommonplace"
      "inourhistoryWhenyoumakepoormenwhenyoupermittheconditionstogrowsuchthatth"
      "epoormanassuchwillbeswayedbyhissenseofinjuryagainstthemenwhotrytoholdwha"
      "ttheyimproperlyhavewonwhenthatdaycomesthemostawfulpassionswillbeletloose"
      "anditwillbeanilldayforourcountryNowfriendswhatwewhoareinthismovementaree"
      "ndeavoringtodoisforestallanysuchmovementforjusticenowamovementinwhichwea"
      "skalljustmenofgenerousheartstojoinwiththemenwhofeelintheirsoulsthatliftu"
      "pwardwhichbidsthemrefusetobesatisfiedthemselveswhiletheircountrymenandco"
      "untrywomensufferfromavoidablemiseryNowfriendswhatweProgressivesaretrying"
      "todoistoenrollrichorpoorwhatevertheirsocialorindustrialpositiontostandto"
      "getherforthemostelementaryrightsofgoodcitizenshipthoseelementaryrightswh"
      "icharethefoundationofgoodcitizenshipinthisgreatRepublicofoursAtthispoint"
      "arenewedeffortwasmadetopersuadeMrRoosevelttoconcludehisspeechMyfriendsar"
      "ealittlemorenervousthanIamDontyouwasteanysympathyonmeIhavehadanA1timeinl"
      "ifeandIamhavingitnowIneverinmylifewasinanymovementinwhichIwasabletoserve"
      "withsuchwholehearteddevotionasinthisinwhichIwasabletofeelasIdointhisthat"
      "commonwealIhavefoughtforthegoodofourcommoncountryAndnowfriendsIshallhave"
      "tocutshortmuchofthatspeechthatImeanttogiveyoubutIwanttotouchonjusttwoort"
      "hreepointsInthefirstplacespeakingtoyouhereinMilwaukeeIwishtosaythatthePr"
      "ogressivepartyismakingitsappealstoallourfellowcitizenswithoutanyregardto"
      "theircreedortotheirbirthplaceWedonotregardasessentialthewayinwhichamanwo"
      "rshipshisGodorasbeingaffectedbywherehewasbornWeregarditasamatterofspirit"
      "andpurposeInNewYorkwhileIwaspolicecommissionerthetwomenfromwhomIgotthemo"
      "stassistancewereJacobRiiswhowasborninDenmarkandArthurvonBriesenwhowasbor"
      "ninGermanybothofthemasfineexamplesofthebestandhighestAmericancitizenship"
      "asyoucouldfindinanypartofthiscountryIhavejustbeenintroducedbyoneofyourow"
      "nmenhereHenryCochemsHisgrandfatherhisfatherandthatfatherssevenbrothersal"
      "lservedintheUnitedStatesarmyandtheyentereditfouryearsaftertheyhadcometot"
      "hiscountryfromGermanyTwoofthemlefttheirlivesspenttheirlivesonthefieldofb"
      "attleIamallrightIamalittlesoreAnybodyhasarighttobesorewithabulletinhimYo"
      "uwouldfindthatifIwasinbattlenowIwouldbeleadingmymenjustthesameJustthesam"
      "ewayIamgoingtomakethisspeechAtonetimeIpromotedfivemenforgallantryonthefi"
      "eldofbattleAfterwardinmakingsomeinquiriesaboutthemIfoundthattwoofthemwer"
      "eProtestantstwoCatholicandoneaJewOneProtestantcamefromGermanyandonewasbo"
      "rninIrelandIdidnotpromotethembecauseoftheirreligionItjusthappenedthatway"
      "IfallfiveofthemhadbeenJewsIwouldhavepromotedthemorifallfiveofthemhadbeen"
      "ProtestantsIwouldhavepromotedthemoriftheyhadbeenCatholicsInthatregimentI"
      "hadamanborninItalywhodistinguishedhimselfbygallantrytherewasanotheryoung"
      "fellowasonofPolishparentsandanotherwhocameherewhenhewasachildfromBohemia"
      "wholikewisedistinguishedthemselvesandfriendsIassureyouthatIwasincapableo"
      "fconsideringanyquestionwhateverbuttheworthofeachindividualasafightingman"
      "IfhewasagoodfightingmanthenIsawthatUncleSamgotthebenefitofitThatisallIma"
      "kethesameappealtoourcitizenshipIaskinourciviclifethatweinthesamewaypayhe"
      "edonlytothemansqualityofcitizenshiptorepudiateastheworstenemythatwecanha"
      "vewhoevertriestogetustodiscriminatefororagainstanymanbecauseofhiscreedor"
      "birthplaceNowfriendsinthesamewayIwantoutpeopletostandbyoneanotherwithout"
      "regardtodifferencesorclassoroccupationIhavealwaysstoodbylaborunionsIamgo"
      "ingtomakeoneomissiontonightIhavepreparedmyspeechbecauseMrWilsonhadseenfi"
      "ttoattackmebyshowinguphisrecordincomparisonwithmineButIamnotgoingtodotha"
      "ttonightIamgoingtosimplyspeakofwhatImyselfhavedoneandwhatIthinkoughttobe"
      "doneinthiscountryofoursItisessentialthathereshouldbeorganizationsoflabor"
      "ThisisaneraoforganizationCapitalorganizesandthereforelabormustorganizeMy"
      "appealfororganizedlaboristwofoldtotheoutsiderandthecapitalistImakemyappe"
      "altotreatthelaborerfairlytorecognizethefactthathemustorganizethattheremu"
      "stbesuchorganizationthatthelaboringmanmustorganizeforhisownprotectionand"
      "thatitisthedutyoftherestofustohelphimandnothinderhiminorganizingThatison"
      "ehalfappealthatImakeNowtheotherhalfistothelabormanhimselfMyappealtohimis"
      "torememberthatashewantsjusticesohemustdojusticeIwanteverylabormaneveryla"
      "borleadereveryorganizedunionmantotaketheleadindenouncingdisorderandinden"
      "ouncingtheincitingofriotthatinthiscountryweshallproceedundertheprotectio"
      "nofourlawsandwithallrespecttothelawsIwantthelabormentofeelintheirturntha"
      "texactlyasjusticemustbedonethemsotheymustdojusticeTheymustbeartheirdutya"
      "scitizenstheirdutytothisgreatcountryofoursandthattheymustnotrestcontentu"
      "nlesstheydothatdutytothefullestdegreeIknowthesedoctorswhentheygetholdofm"
      "ewillneverletmegobackandtherearejustafewmorethingsthatIwanttosaytoyouAnd"
      "hereIhavegottomakeonecomparisonbetweenMrWilsonandmyselfsimplybecauseheha"
      "sinviteditandIcannotshrinkfromitMrWilsonhasseenfittoattackmetosaythatIdi"
      "dnotdomuchagainstthetrustswhenIwasPresidentIhavegottwoanswerstomaketotha"
      "tInthefirstplacewhatIdidandthenIwanttocomparewhatIdidwhenIwasPresidentwi"
      "thwhatMrWilsondidnotdowhenhewasgovernorWhenItooktheofficetheantitrustlaw"
      "waspracticallyadeadletterandtheinterstatecommercelawinaspooraconditionIh"
      "adtorevivebothlawsIdidIenforcedbothItwillbeeasyenoughtodonowwhatIdidthen"
      "butthereasonthatitiseasynowisbecauseIdiditwhenitwashardNobodywasdoingany"
      "thingIfoundspeedilythattheinterstatecommercelawbybeingmadeperfectcouldbe"
      "madeamostusefulinstrumentforhelpingsolvesomeofourindustrialproblemsSowit"
      "htheantitrustlawIspeedilyfoundoutthatalmosttheonlypositivegoodachievedby"
      "suchasuccessfullawsuitastheNorthernSecuritiessuitforinstancewasinestabli"
      "shingtheprinciplethatthegovernmentwassupremeoverthebigcorporationbutbyit"
      "selfthatthelawdidnotaccomplishanyofthethingsthatweoughttohaveaccomplishe"
      "dandsoIbegantofightfortheamendmentofthelawalongthelinesoftheinterstateco"
      "mmercelawandnowweproposeweProgressivestoestablishandinterstatecommission"
      "havingthesamepoweroverindustrialconcernsthattheInterstateCommerceCommiss"
      "ionhasoverrailroadssothatwheneverthereisinthefutureadecisionrenderedinsu"
      "chimportantmattersastherecentsuitsagainsttheStandardOilthesugarnonotthat"
      "TobaccoTobaccoTrustwewillhaveacommissionwhichwillseethatthedecreeoftheco"
      "urtisreallymadeeffectivethatitisnotmadeamerelynominaldecreeOuropponentsh"
      "avesaidthatweintendtolegalizemonopolyNonsenseTheyhavelegalizedmonopolyAt"
      "thismomenttheStandardOilandTobaccoTrustmonopoliesarelegalizedtheyarebein"
      "gcarriedonunderthedecreeoftheSupremeCourtOurproposalisreallytobreakupmon"
      "opolyOurproposalistolaydowncertainrequirementsandthentorequirethecommerc"
      "ecommissiontheindustrialcommissiontoseethatthetrustsliveuptothoserequire"
      "mentsOuropponentshavespokenasifweweregoingtoletthecommissiondeclarewhatt"
      "hoserequirementsshouldbeNotatallWearegoingtoputtherequirementsinthelawan"
      "dthenseethatthecommissionrequiresthemtoobeythatlawAndnowfriendsasMrWilso"
      "nhasinvitedthecomparisonIonlywanttosaythisMrWilsonhassaidthattheStatesar"
      "etheproperauthoritiestodealwiththetrustsWellabouteightypercentofthetrust"
      "sareorganizedinNewJerseyTheStandardOiltheTobaccotheSugartheBeefallthoset"
      "rustsareorganizedinthestateofNewJerseyandthelawsofNewJerseysaythattheirc"
      "harterscanatanytimebeamendedorrepealediftheymisbehavethemselvesandgiveth"
      "egovernmentamplepowertoactaboutthoselawsandMrWilsonhasbeengovernorayeara"
      "ndninemonthsandhehasnotopenedhislipsThechapterdescribingwhatMrWilsonhasd"
      "oneabouttrustsinNewJerseywouldreadpreciselylikeachapterdescribingsnakesi"
      "nIrelandwhichranTherearenosnakesinIrelandMrWilsonhasdonepreciselyandexac"
      "tlynothingaboutthetrustsItellyouandItoldyouatthebeginningIdonotsayanythi"
      "ngonthestumpthatIdonotbelieveIdonotsayanythingIdonotknowLetanyofMrWilson"
      "sfriendsonTuesdaypointoutonethingorletMrWilsonpointoutonethingthathehasd"
      "oneaboutthetrustsasgovernorofNewJerseyAndnowfriendsthereisonethingIwantt"
      "osayespeciallytoyoupeoplehereinWisconsinAllthatIhavesaidsofariswhatIwoul"
      "dsayinanypartoftheUnionIhaveapeculiarrighttoaskthatinthisgreatcontestyou"
      "menandwomenofWisconsinshallstandwithusYouhavetakentheleadinprogressivemo"
      "vementshereinWisconsinYouhavetaughttherestofustolooktoyouforinspirationa"
      "ndleadershipNowfriendsyouhavemadethatmovementherelocallyYouwillbeingdoin"
      "gadreadfulinjusticetoyourselvesyouwillbedoingadreadfulinjusticetotherest"
      "ofusthroughouttheUnionifyoufailtostandwithusnowthatwearemakingthisnation"
      "almovementWhatIamabouttosaynowIwantyotounderstandIfIspeakofMrWilsonIspea"
      "kwithnomindofbitternessImerelywanttodiscussthedifferenceofpolicybetweent"
      "heProgressiveandtheDemocraticpartyandtoaskyoutothinkforyourselveswhichpa"
      "rtyyouwillfollowIwillsaythatfriendsbecausetheRepublicanpartyisbeatenNobo"
      "dyneedstohaveanyideathatanythingcanbedonewiththeRepublicanpartyWhentheRe"
      "publicanpartynottheRepublicanpartywhenthebossesincontroloftheRepublicanp"
      "artytheBarnesesandPenroseslastJunestolethenominationandwreckedtheRepubli"
      "canpartyforgoodandallIwanttopointouttoyouthatnominallytheystolethatnomin"
      "ationfrommebutitwasreallyfromyouTheydidnotlikemeandthelongertheylivethel"
      "esscausetheywillhavetolikemeButwhiletheydontlikemetheydreadyouYouarethep"
      "eoplethattheydreadTheydreadthepeoplethemselvesandthosebossesandthebigspe"
      "cialinterestsbehindthemmadeuptheirmindthattheywouldratherseetheRepublica"
      "npartywreckedthanseeitcomeunderthecontrolofthepeoplethemselvesSoIamnotde"
      "alingwiththeRepublicanpartyThereareonlytwowaysyoucanvotethisyearYoucanbe"
      "progressiveorreactionaryWhetheryouvoteRepublicanorDemocraticitdoesnotmak"
      "eadifferenceyouarevotingreactionaryNowtheDemocraticpartyinitsplatformand"
      "throughtheutterancesofMrWilsonhasdistinctlycommitteditselftotheoldflintl"
      "ockmuzzleloadeddoctrineofStatesrightsandIhavesaiddistinctlyweareforpeopl"
      "esrightsWearefortherightsofthepeopleIftheycanbeobtainedbestthroughNation"
      "alGovernmentthenwearefornationalrightsWeareforpeoplesrightshoweveritisne"
      "cessarytosecurethemMrWilsonhasmadealongessayagainstSenatorBeveridgesbill"
      "toabolishchildlaborItisthesamekindofargumentthatwouldbemadeagainstourbil"
      "ltoprohibitwomenfromworkingmorethaneighthoursadayinindustryItisthesameki"
      "ndofargumentthatwouldhavetobemadeifitistrueitwouldapplyequallyagainstour"
      "proposaltoinsistthatincontinuousindustriesthereshallbebylawonedaysrestin"
      "sevenandthreeshifteighthourdayYouhavelaborlawshereinWisconsinandchambero"
      "fcommercewilltellyouthatbecauseofthatfactthereareindustriesthatwillnotco"
      "metoWisconsinTheyprefertostayoutsidewheretheycanworkchildrenoftenderyear"
      "swheretheycanworkwomenfourteenandsixteenhoursadaywhereifitisacontinuousi"
      "ndustrytheycanworkmentwelvehoursadayandsevendaysaweekNowfriendsIknowthat"
      "youofWisconsinwouldneverrepealthoselawseveniftheyareatyourcommercialhurt"
      "justasIamtryingtogetNewYorktoadoptsuchlawseventhoughitwillbetotheNewYork"
      "scommercialhurtButifpossibleIwanttoarrangeitsothatwecanhavejusticewithou"
      "tcommercialhurtandyoucanonlygetthatifyouhavejusticeenforcednationallyYou"
      "wontbeburdenedinWisconsinwithindustriesnotcomingtotheStateifthesamegoodl"
      "awsareextendedallovertheotherStatesDoyouseewhatImean?"
      "TheStatesallcompeteinacommonmarketanditisnotjusticetotheemployersofaStat"
      "ethathasenforcedjustandproperlawstohavethemexposedtothecompetitionofanot"
      "herStatewherenosuchlawsareenforcedNowtheDemocraticplatformandtheirspeake"
      "rsdeclareweshallnothavesuchlawsMrWilsonhasdistinctlydeclaredthatweshalln"
      "othaveanationallawtoprohibitthelaborofchildrentoprohibitchildlaborHehasd"
      "istinctlydeclaredthatweshallnothavealawtoestablishaminimumwageforwomenIa"
      "skyoutolookatourdeclarationandhearandreadourplatformaboutsocialandindust"
      "rialjusticeandthenfriendsvotefortheProgressiveticketwithoutregardtomewit"
      "houtregardtomypersonalityforonlybyvotingforthatplatformcanyoubetruetothe"
      "causeofprogressthroughoutthisUnionTRwasshotinanassassinationattemptbyJoh"
      "nSchrankwhohadbeenhavingdisturbingdreamsaboutTRspredecessorWilliamMcKinl"
      "eyandalsothoughtthatnopresidentshouldservemorethantwotermsSchrankspentth"
      "erestofhislifeinamentalinstitutionNoonecametovisithimHediedshortlyafterF"
      "ranklinDelanoRooseveltTRsfifthcousinwaselectedtoathirdtermSchrankhadstal"
      "kedTRforthousandsofmilesbeforegettingaclearshotathiminMilwaukeeSchrankwa"
      "scaughtonthespotFriendsIshallaskyoutobeasquietaspossibleIdontknowwhether"
      "youfullyunderstandthatIhavejustbeenshotbutittakesmorethanthattokillaBull"
      "MooseButfortunatelyIhadmymanuscriptsoyouseeIwasgoingtomakealongspeechand"
      "thereisabulletthereiswherethebulletwentthroughanditprobablysavedmefromit"
      "goingintomyheartThebulletisinmenowsothatIcannotmakeaverylongspeechbutIwi"
      "lltrymybestAndnowfriendsIwanttotakeadvantageofthisincidenttosayawordofso"
      "lemnwarningtomyfellowcountrymenFirstofallIwanttosaythisaboutmyselfIhavea"
      "ltogethertooimportantthingstothinkoftofeelanyconcernovermyowndeathandnow"
      "IcannotspeaktoyouinsincerelywithinfiveminutesofbeingshotIamtellingyouthe"
      "literaltruthwhenIsaythatmyconcernisformanyotherthingsItisnotintheleastfo"
      "rmyownlifeIwantyoutounderstandthatIamaheadofthegameanywayNomanhashadahap"
      "pierlifethanIhaveledahappierlifeineverywayIhavebeenabletodocertainthings"
      "thatIgreatlywishedtodoandIaminterestedindoingotherthingsIcantellyouwitha"
      "bsolutetruthfulnessthatIamverymuchuninterestedinwhetherIamshotornotItwas"
      "justaswhenIwascolonelofmyregimentIalwaysfeltthataprivatewastobeexcusedfo"
      "rfeelingattimessomepangsofanxietyabouthispersonalsafetybutIcannotunderst"
      "andamanfittobeacolonelwhocanpayanyheedtohispersonalsafetywhenheisoccupie"
      "dasheoughttobewiththeabsorbingdesiretodohisdutyIaminthiscausewithmywhole"
      "heartandsoulIbelievethattheProgressivemovementismakinglifealittleeasierf"
      "orallourpeopleamovementtotrytotaketheburdensoffthemenandespeciallythewom"
      "enandchildrenofthiscountryIamabsorbedinthesuccessofthatmovementFriendsIa"
      "skyounowthiseveningtoacceptwhatIamsayingasabsolutelytruewhenItellyouIamn"
      "otthinkingofmyownsuccessIamnotthinkingofmylifeorofanythingconnectedwithm"
      "epersonallyIamthinkingofthemovementIsaythisbywayofintroductionbecauseIwa"
      "nttosaysomethingveryserioustoourpeopleandespeciallytothenewspapersIdontk"
      "nowanythingaboutwhothemanwaswhoshotmetonightHewasseizedatoncebyoneofthes"
      "tenographersinmypartyMrMartinandIsupposeisnowinthehandsofthepoliceHeshot"
      "tokillHeshottheshotthebulletwentinhereIwillshowyouIamgoingtoaskyoutobeas"
      "quietaspossibleforIamnotabletogivetochallengeofthebullmoosequiteasloudly"
      "NowIdonotknowwhohewasorwhatherepresentedHewasacowardHestoodinthedarkness"
      "inthecrowdaroundtheautomobileandwhentheycheeredmeandIgotuptobowhestepped"
      "forwardandshotmeinthedarknessNowfriendsofcourseIdonotknowasIsayanythinga"
      "bouthimbutitisaverynaturalthingthatweakandviciousmindsshouldbeinflamedto"
      "actsofviolencebythekindofawfulmendacityandabusethathavebeenheapeduponmef"
      "orthelastthreemonthsbythepapersintheinterestofnotonlyMrDebsbutofMrWilson"
      "andMrTaftFriendsIwilldisownandrepudiateanymanofmypartywhoattackswithsuch"
      "foulslanderandabuseanyopponentofanyotherpartyandnowIwishtosayseriouslyto"
      "allthedailynewspaperstotheRepublicanstheDemocratandSocialistpartiesthatt"
      "heycannotmonthinmonthoutandyearinandyearoutmakethekindofuntruthfulofbitt"
      "erassaultthattheyhavemadeandnotexpectthatbrutalviolentnaturesorbrutaland"
      "violentcharactersespeciallywhenthebrutalityisaccompaniedbyanotverystrong"
      "mindtheycannotexpectthatsuchnatureswillbeunaffectedbyitNowfriendsIamnots"
      "peakingformyselfatallIgiveyoumywordIdonotcarearapaboutbeingshotnotarapIh"
      "avehadagoodmanyexperiencesinmytimeandthisisoneofthemWhatIcareforismycoun"
      "tryIwishIwereabletoimpressuponmypeopleourpeoplethedutytofeelstronglybutt"
      "ospeakthetruthoftheiropponentsIsaynowIhaveneversaidonewordonethestumpaga"
      "instanyopponentthatIcannotdefendIhavesaidnothingthatIcouldnotsubstantiat"
      "eandnothingthatIoughtnottohavesaidnothingthatInothingthatlookingbackatIw"
      "ouldnotsayagainNowfriendsitoughtnottobetoomuchtoaskthatouropponents["
      "speakingtosomeoneonthestage]"
      "IamnotsickatallIamallrightIcannottellyouofwhatinfinitesimalimportanceIre"
      "gardthisincidentascomparedwiththegreatissuesatstakeinthiscampaignandIask"
      "itnotformysakenottheleastintheworldbutforthesakeofcommoncountrythattheym"
      "akeuptheirmindstospeakonlythetruthandnotusethatkindofslanderandmendacity"
      "whichiftakenseriouslymustinciteweakandviolentnaturestocrimesofviolenceDo"
      "ntyoumakeanymistakeDontyoupitymeIamallrightIamallrightandyoucannotescape"
      "listeningtothespeecheitherAndnowfriendsthisincidentthathasjustoccurredth"
      "isefforttoassassinatemeemphasizestoapeculiardegreetheneedoftheProgressiv"
      "emovementFriendseverygoodcitizenoughttodoeverythinginhisorherpowertoprev"
      "entthecomingofthedaywhenweshallseeinthiscountrytworecognizedcreedsfighti"
      "ngoneanotherwhenweshallseethecreedoftheHavenotsarraignedagainstthecreedo"
      "ftheHavesWhenthatdaycomesthensuchincidentsasthistonightwillbecommonplace"
      "inourhistoryWhenyoumakepoormenwhenyoupermittheconditionstogrowsuchthatth"
      "epoormanassuchwillbeswayedbyhissenseofinjuryagainstthemenwhotrytoholdwha"
      "ttheyimproperlyhavewonwhenthatdaycomesthemostawfulpassionswillbeletloose"
      "anditwillbeanilldayforourcountryNowfriendswhatwewhoareinthismovementaree"
      "ndeavoringtodoisforestallanysuchmovementforjusticenowamovementinwhichwea"
      "skalljustmenofgenerousheartstojoinwiththemenwhofeelintheirsoulsthatliftu"
      "pwardwhichbidsthemrefusetobesatisfiedthemselveswhiletheircountrymenandco"
      "untrywomensufferfromavoidablemiseryNowfriendswhatweProgressivesaretrying"
      "todoistoenrollrichorpoorwhatevertheirsocialorindustrialpositiontostandto"
      "getherforthemostelementaryrightsofgoodcitizenshipthoseelementaryrightswh"
      "icharethefoundationofgoodcitizenshipinthisgreatRepublicofoursAtthispoint"
      "arenewedeffortwasmadetopersuadeMrRoosevelttoconcludehisspeechMyfriendsar"
      "ealittlemorenervousthanIamDontyouwasteanysympathyonmeIhavehadanA1timeinl"
      "ifeandIamhavingitnowIneverinmylifewasinanymovementinwhichIwasabletoserve"
      "withsuchwholehearteddevotionasinthisinwhichIwasabletofeelasIdointhisthat"
      "commonwealIhavefoughtforthegoodofourcommoncountryAndnowfriendsIshallhave"
      "tocutshortmuchofthatspeechthatImeanttogiveyoubutIwanttotouchonjusttwoort"
      "hreepointsInthefirstplacespeakingtoyouhereinMilwaukeeIwishtosaythatthePr"
      "ogressivepartyismakingitsappealstoallourfellowcitizenswithoutanyregardto"
      "theircreedortotheirbirthplaceWedonotregardasessentialthewayinwhichamanwo"
      "rshipshisGodorasbeingaffectedbywherehewasbornWeregarditasamatterofspirit"
      "andpurposeInNewYorkwhileIwaspolicecommissionerthetwomenfromwhomIgotthemo"
      "stassistancewereJacobRiiswhowasborninDenmarkandArthurvonBriesenwhowasbor"
      "ninGermanybothofthemasfineexamplesofthebestandhighestAmericancitizenship"
      "asyoucouldfindinanypartofthiscountryIhavejustbeenintroducedbyoneofyourow"
      "nmenhereHenryCochemsHisgrandfatherhisfatherandthatfatherssevenbrothersal"
      "lservedintheUnitedStatesarmyandtheyentereditfouryearsaftertheyhadcometot"
      "hiscountryfromGermanyTwoofthemlefttheirlivesspenttheirlivesonthefieldofb"
      "attleIamallrightIamalittlesoreAnybodyhasarighttobesorewithabulletinhimYo"
      "uwouldfindthatifIwasinbattlenowIwouldbeleadingmymenjustthesameJustthesam"
      "ewayIamgoingtomakethisspeechAtonetimeIpromotedfivemenforgallantryonthefi"
      "eldofbattleAfterwardinmakingsomeinquiriesaboutthemIfoundthattwoofthemwer"
      "eProtestantstwoCatholicandoneaJewOneProtestantcamefromGermanyandonewasbo"
      "rninIrelandIdidnotpromotethembecauseoftheirreligionItjusthappenedthatway"
      "IfallfiveofthemhadbeenJewsIwouldhavepromotedthemorifallfiveofthemhadbeen"
      "ProtestantsIwouldhavepromotedthemoriftheyhadbeenCatholicsInthatregimentI"
      "hadamanborninItalywhodistinguishedhimselfbygallantrytherewasanotheryoung"
      "fellowasonofPolishparentsandanotherwhocameherewhenhewasachildfromBohemia"
      "wholikewisedistinguishedthemselvesandfriendsIassureyouthatIwasincapableo"
      "fconsideringanyquestionwhateverbuttheworthofeachindividualasafightingman"
      "IfhewasagoodfightingmanthenIsawthatUncleSamgotthebenefitofitThatisallIma"
      "kethesameappealtoourcitizenshipIaskinourciviclifethatweinthesamewaypayhe"
      "edonlytothemansqualityofcitizenshiptorepudiateastheworstenemythatwecanha"
      "vewhoevertriestogetustodiscriminatefororagainstanymanbecauseofhiscreedor"
      "birthplaceNowfriendsinthesamewayIwantoutpeopletostandbyoneanotherwithout"
      "regardtodifferencesorclassoroccupationIhavealwaysstoodbylaborunionsIamgo"
      "ingtomakeoneomissiontonightIhavepreparedmyspeechbecauseMrWilsonhadseenfi"
      "ttoattackmebyshowinguphisrecordincomparisonwithmineButIamnotgoingtodotha"
      "ttonightIamgoingtosimplyspeakofwhatImyselfhavedoneandwhatIthinkoughttobe"
      "doneinthiscountryofoursItisessentialthathereshouldbeorganizationsoflabor"
      "ThisisaneraoforganizationCapitalorganizesandthereforelabormustorganizeMy"
      "appealfororganizedlaboristwofoldtotheoutsiderandthecapitalistImakemyappe"
      "altotreatthelaborerfairlytorecognizethefactthathemustorganizethattheremu"
      "stbesuchorganizationthatthelaboringmanmustorganizeforhisownprotectionand"
      "thatitisthedutyoftherestofustohelphimandnothinderhiminorganizingThatison"
      "ehalfappealthatImakeNowtheotherhalfistothelabormanhimselfMyappealtohimis"
      "torememberthatashewantsjusticesohemustdojusticeIwanteverylabormaneveryla"
      "borleadereveryorganizedunionmantotaketheleadindenouncingdisorderandinden"
      "ouncingtheincitingofriotthatinthiscountryweshallproceedundertheprotectio"
      "nofourlawsandwithallrespecttothelawsIwantthelabormentofeelintheirturntha"
      "texactlyasjusticemustbedonethemsotheymustdojusticeTheymustbeartheirdutya"
      "scitizenstheirdutytothisgreatcountryofoursandthattheymustnotrestcontentu"
      "nlesstheydothatdutytothefullestdegreeIknowthesedoctorswhentheygetholdofm"
      "ewillneverletmegobackandtherearejustafewmorethingsthatIwanttosaytoyouAnd"
      "hereIhavegottomakeonecomparisonbetweenMrWilsonandmyselfsimplybecauseheha"
      "sinviteditandIcannotshrinkfromitMrWilsonhasseenfittoattackmetosaythatIdi"
      "dnotdomuchagainstthetrustswhenIwasPresidentIhavegottwoanswerstomaketotha"
      "tInthefirstplacewhatIdidandthenIwanttocomparewhatIdidwhenIwasPresidentwi"
      "thwhatMrWilsondidnotdowhenhewasgovernorWhenItooktheofficetheantitrustlaw"
      "waspracticallyadeadletterandtheinterstatecommercelawinaspooraconditionIh"
      "adtorevivebothlawsIdidIenforcedbothItwillbeeasyenoughtodonowwhatIdidthen"
      "butthereasonthatitiseasynowisbecauseIdiditwhenitwashardNobodywasdoingany"
      "thingIfoundspeedilythattheinterstatecommercelawbybeingmadeperfectcouldbe"
      "madeamostusefulinstrumentforhelpingsolvesomeofourindustrialproblemsSowit"
      "htheantitrustlawIspeedilyfoundoutthatalmosttheonlypositivegoodachievedby"
      "suchasuccessfullawsuitastheNorthernSecuritiessuitforinstancewasinestabli"
      "shingtheprinciplethatthegovernmentwassupremeoverthebigcorporationbutbyit"
      "selfthatthelawdidnotaccomplishanyofthethingsthatweoughttohaveaccomplishe"
      "dandsoIbegantofightfortheamendmentofthelawalongthelinesoftheinterstateco"
      "mmercelawandnowweproposeweProgressivestoestablishandinterstatecommission"
      "havingthesamepoweroverindustrialconcernsthattheInterstateCommerceCommiss"
      "ionhasoverrailroadssothatwheneverthereisinthefutureadecisionrenderedinsu"
      "chimportantmattersastherecentsuitsagainsttheStandardOilthesugarnonotthat"
      "TobaccoTobaccoTrustwewillhaveacommissionwhichwillseethatthedecreeoftheco"
      "urtisreallymadeeffectivethatitisnotmadeamerelynominaldecreeOuropponentsh"
      "avesaidthatweintendtolegalizemonopolyNonsenseTheyhavelegalizedmonopolyAt"
      "thismomenttheStandardOilandTobaccoTrustmonopoliesarelegalizedtheyarebein"
      "gcarriedonunderthedecreeoftheSupremeCourtOurproposalisreallytobreakupmon"
      "opolyOurproposalistolaydowncertainrequirementsandthentorequirethecommerc"
      "ecommissiontheindustrialcommissiontoseethatthetrustsliveuptothoserequire"
      "mentsOuropponentshavespokenasifweweregoingtoletthecommissiondeclarewhatt"
      "hoserequirementsshouldbeNotatallWearegoingtoputtherequirementsinthelawan"
      "dthenseethatthecommissionrequiresthemtoobeythatlawAndnowfriendsasMrWilso"
      "nhasinvitedthecomparisonIonlywanttosaythisMrWilsonhassaidthattheStatesar"
      "etheproperauthoritiestodealwiththetrustsWellabouteightypercentofthetrust"
      "sareorganizedinNewJerseyTheStandardOiltheTobaccotheSugartheBeefallthoset"
      "rustsareorganizedinthestateofNewJerseyandthelawsofNewJerseysaythattheirc"
      "harterscanatanytimebeamendedorrepealediftheymisbehavethemselvesandgiveth"
      "egovernmentamplepowertoactaboutthoselawsandMrWilsonhasbeengovernorayeara"
      "ndninemonthsandhehasnotopenedhislipsThechapterdescribingwhatMrWilsonhasd"
      "oneabouttrustsinNewJerseywouldreadpreciselylikeachapterdescribingsnakesi"
      "nIrelandwhichranTherearenosnakesinIrelandMrWilsonhasdonepreciselyandexac"
      "tlynothingaboutthetrustsItellyouandItoldyouatthebeginningIdonotsayanythi"
      "ngonthestumpthatIdonotbelieveIdonotsayanythingIdonotknowLetanyofMrWilson"
      "sfriendsonTuesdaypointoutonethingorletMrWilsonpointoutonethingthathehasd"
      "oneaboutthetrustsasgovernorofNewJerseyAndnowfriendsthereisonethingIwantt"
      "osayespeciallytoyoupeoplehereinWisconsinAllthatIhavesaidsofariswhatIwoul"
      "dsayinanypartoftheUnionIhaveapeculiarrighttoaskthatinthisgreatcontestyou"
      "menandwomenofWisconsinshallstandwithusYouhavetakentheleadinprogressivemo"
      "vementshereinWisconsinYouhavetaughttherestofustolooktoyouforinspirationa"
      "ndleadershipNowfriendsyouhavemadethatmovementherelocallyYouwillbeingdoin"
      "gadreadfulinjusticetoyourselvesyouwillbedoingadreadfulinjusticetotherest"
      "ofusthroughouttheUnionifyoufailtostandwithusnowthatwearemakingthisnation"
      "almovementWhatIamabouttosaynowIwantyotounderstandIfIspeakofMrWilsonIspea"
      "kwithnomindofbitternessImerelywanttodiscussthedifferenceofpolicybetweent"
      "heProgressiveandtheDemocraticpartyandtoaskyoutothinkforyourselveswhichpa"
      "rtyyouwillfollowIwillsaythatfriendsbecausetheRepublicanpartyisbeatenNobo"
      "dyneedstohaveanyideathatanythingcanbedonewiththeRepublicanpartyWhentheRe"
      "publicanpartynottheRepublicanpartywhenthebossesincontroloftheRepublicanp"
      "artytheBarnesesandPenroseslastJunestolethenominationandwreckedtheRepubli"
      "canpartyforgoodandallIwanttopointouttoyouthatnominallytheystolethatnomin"
      "ationfrommebutitwasreallyfromyouTheydidnotlikemeandthelongertheylivethel"
      "esscausetheywillhavetolikemeButwhiletheydontlikemetheydreadyouYouarethep"
      "eoplethattheydreadTheydreadthepeoplethemselvesandthosebossesandthebigspe"
      "cialinterestsbehindthemmadeuptheirmindthattheywouldratherseetheRepublica"
      "npartywreckedthanseeitcomeunderthecontrolofthepeoplethemselvesSoIamnotde"
      "alingwiththeRepublicanpartyThereareonlytwowaysyoucanvotethisyearYoucanbe"
      "progressiveorreactionaryWhetheryouvoteRepublicanorDemocraticitdoesnotmak"
      "eadifferenceyouarevotingreactionaryNowtheDemocraticpartyinitsplatformand"
      "throughtheutterancesofMrWilsonhasdistinctlycommitteditselftotheoldflintl"
      "ockmuzzleloadeddoctrineofStatesrightsandIhavesaiddistinctlyweareforpeopl"
      "esrightsWearefortherightsofthepeopleIftheycanbeobtainedbestthroughNation"
      "alGovernmentthenwearefornationalrightsWeareforpeoplesrightshoweveritisne"
      "cessarytosecurethemMrWilsonhasmadealongessayagainstSenatorBeveridgesbill"
      "toabolishchildlaborItisthesamekindofargumentthatwouldbemadeagainstourbil"
      "ltoprohibitwomenfromworkingmorethaneighthoursadayinindustryItisthesameki"
      "ndofargumentthatwouldhavetobemadeifitistrueitwouldapplyequallyagainstour"
      "proposaltoinsistthatincontinuousindustriesthereshallbebylawonedaysrestin"
      "sevenandthreeshifteighthourdayYouhavelaborlawshereinWisconsinandchambero"
      "fcommercewilltellyouthatbecauseofthatfactthereareindustriesthatwillnotco"
      "metoWisconsinTheyprefertostayoutsidewheretheycanworkchildrenoftenderyear"
      "swheretheycanworkwomenfourteenandsixteenhoursadaywhereifitisacontinuousi"
      "ndustrytheycanworkmentwelvehoursadayandsevendaysaweekNowfriendsIknowthat"
      "youofWisconsinwouldneverrepealthoselawseveniftheyareatyourcommercialhurt"
      "justasIamtryingtogetNewYorktoadoptsuchlawseventhoughitwillbetotheNewYork"
      "scommercialhurtButifpossibleIwanttoarrangeitsothatwecanhavejusticewithou"
      "tcommercialhurtandyoucanonlygetthatifyouhavejusticeenforcednationallyYou"
      "wontbeburdenedinWisconsinwithindustriesnotcomingtotheStateifthesamegoodl"
      "awsareextendedallovertheotherStatesDoyouseewhatImean?"
      "TheStatesallcompeteinacommonmarketanditisnotjusticetotheemployersofaStat"
      "ethathasenforcedjustandproperlawstohavethemexposedtothecompetitionofanot"
      "herStatewherenosuchlawsareenforcedNowtheDemocraticplatformandtheirspeake"
      "rsdeclareweshallnothavesuchlawsMrWilsonhasdistinctlydeclaredthatweshalln"
      "othaveanationallawtoprohibitthelaborofchildrentoprohibitchildlaborHehasd"
      "istinctlydeclaredthatweshallnothavealawtoestablishaminimumwageforwomenIa"
      "skyoutolookatourdeclarationandhearandreadourplatformaboutsocialandindust"
      "rialjusticeandthenfriendsvotefortheProgressiveticketwithoutregardtomewit"
      "houtregardtomypersonalityforonlybyvotingforthatplatformcanyoubetruetothe"
      "causeofprogressthroughoutthisUnion";
  int kmpNext[PATTERN_SIZE];
  int n_matches[1];
  int int_pattern[PATTERN_SIZE];
  int int_input[STRING_SIZE];

  for (int i = 0; i < PATTERN_SIZE; i++) {
    int_pattern[i] = (int)pattern[i];
  }
  for (int i = 0; i < STRING_SIZE; i++) {
    int_input[i] = (int)input[i];
  }

  hls_top(STRING_SIZE, int_pattern, int_input, kmpNext, n_matches);
  return 0;
}
