# Configuration file for LLVM IR Transformer
# Maps array references to capability indices

["%key_array"]
"cap" = 0
"device" = "host"
"size" = 32
#"omit_array" = true

["%enckey_array"]
"cap" = 1
"device" = "host"
"size" = 32
#"omit_array" = true

["%deckey_array"]
"cap" = 2
"device" = "host"
"size" = 32
#"omit_array" = true

["%key_local"]
"cap" = 3
"device" = "local"
"size" = 32
#"omit_array" = true

["%buf"]
"cap" = 4
"device" = "local"
"size" = 16
#"omit_array" = true

["%aes_key"]
"cap" = 5
"device" = "local"
"size" = 32
#"omit_array" = true

["%enc_key"]
"cap" = 6
"device" = "local"
"size" = 32
#"omit_array" = true

["%dec_key"]
"cap" = 7
"device" = "local"
"size" = 32
#"omit_array" = true

["@sbox"]
"cap" = 8
"device" = "local"
"size" = 256
#"omit_array" = true
