# Configuration file for LLVM IR Transformer
# Maps array references to capability indices

["%xa"]
"cap" = 0
"device" = "host"
"size" = 1

["%xb"]
"cap" = 1
"device" = "host"
"size" = 1


["%temp"]
"cap" = 2
"device" = "local"
"size" = 2048

["%a"]
"cap" = 3
"device" = "local"
"size" = 2048
