# Configuration file for LLVM IR Transformer
# Maps array references to capability indices

["%xforce_x"]
"cap" = 0
"device" = "host"
"size" = 256

["%xforce_y"]
"cap" = 1
"device" = "host"
"size" = 256

["%xforce_z"]
"cap" = 2
"device" = "host"
"size" = 256

["%xposition_x"]
"cap" = 3
"device" = "host"
"size" = 256

["%xposition_y"]
"cap" = 4
"device" = "host"
"size" = 256

["%xposition_z"]
"cap" = 5
"device" = "host"
"size" = 256

["%xNL"]
"cap" = 6
"device" = "host"
"size" = 4096

["%force_x"]
"cap" = 7
"device" = "local"
"size" = 256

["%force_y"]
"cap" = 8
"device" = "local"
"size" = 256

["%force_z"]
"cap" = 9
"device" = "local"
"size" = 256

["%position_x"]
"cap" = 10
"device" = "local"
"size" = 256

["%position_y"]
"cap" = 11
"device" = "local"
"size" = 256

["%position_z"]
"cap" = 12
"device" = "local"
"size" = 256

["%NL"]
"cap" = 13
"device" = "local"
"size" = 4096
