# Configuration file for LLVM IR Transformer
# Maps array references to capability indices

["%xorig"]
"cap" = 2
"device" = "host"
"size" = 1

["%xsol"]
"cap" = 1
"device" = "host"
"size" = 1
#"omit_array" = true

["%sol"]
"cap" = 3
"device" = "local"
"size" = 8192
#"omit_array" = true

["%xfilter"]
"cap" = 0
"device" = "host"
"size" = 9
#"omit_array" = true
