# Configuration file for LLVM IR Transformer
# Maps array references to capability indices

["%xnodes_b"]
"cap" = 0
"device" = "host"

["%xnodes_e"]
"cap" = 1
"device" = "host"

["%xedges"]
"cap" = 2
"device" = "host"

["%xlevel"]
"cap" = 3
"device" = "host"

["%xlevel_counts"]
"cap" = 4
"device" = "host"

["%queue"]
"cap" = 5
"device" = "local"
"size" = 256

["%nodes_edge_begin"]
"cap" = 6
"device" = "local"
"size" = 256

["%nodes_edge_end"]
"cap" = 7
"device" = "local"
"size" = 256

["%edges_dst"]
"cap" = 8
"device" = "local"
"size" = 4096

["%level"]
"cap" = 9
"device" = "local"
"size" = 256

["%level_counts"]
"cap" = 10
"device" = "local"
"size" = 10
