# Configuration file for LLVM IR Transformer
# Maps array references to capability indices

["%xweights1"]
"cap" = 0
"device" = "host"
"size" = 256

["%xweights2"]
"cap" = 1
"device" = "host"
"size" = 256

["%xweights3"]
"cap" = 2
"device" = "host"
"size" = 48

["%xbiases1"]
"cap" = 3
"device" = "host"
"size" = 16

["%xbiases2"]
"cap" = 4
"device" = "host"
"size" = 16

["%xbiases3"]
"cap" = 5
"device" = "host"
"size" = 3

["%xtraining_data"]
"cap" = 6
"device" = "host"
"size" = 2608

["%xtraining_targets"]
"cap" = 7
"device" = "host"
"size" = 489

["%weights1"]
"cap" = 8
"device" = "local"
"size" = 256

["%weights2"]
"cap" = 9
"device" = "local"
"size" = 256

["%weights3"]
"cap" = 10
"device" = "local"
"size" = 48

["%biases1"]
"cap" = 11
"device" = "local"
"size" = 16

["%biases2"]
"cap" = 12
"device" = "local"
"size" = 16

["%biases3"]
"cap" = 13
"device" = "local"
"size" = 3

["%training_data"]
"cap" = 14
"device" = "local"
"size" = 2608

["%training_targets"]
"cap" = 15
"device" = "local"
"size" = 489

["%activations1"]
"cap" = 16
"device" = "local"
"size" = 16

["%activations2"]
"cap" = 17
"device" = "local"
"size" = 16

["%activations3"]
"cap" = 18
"device" = "local"
"size" = 3

["%dactivations1"]
"cap" = 19
"device" = "local"
"size" = 16

["%dactivations2"]
"cap" = 20
"device" = "local"
"size" = 16

["%dactivations3"]
"cap" = 21
"device" = "local"
"size" = 3

["%net_outputs"]
"cap" = 22
"device" = "local"
"size" = 3

["%output_difference"]
"cap" = 23
"device" = "local"
"size" = 3

["%delta_weights1"]
"cap" = 24
"device" = "local"
"size" = 256

["%delta_weights2"]
"cap" = 25
"device" = "local"
"size" = 48

["%delta_weights3"]
"cap" = 26
"device" = "local"
"size" = 48

["%oracle_activations1"]
"cap" = 27
"device" = "local"
"size" = 16

["%oracle_activations2"]
"cap" = 28
"device" = "local"
"size" = 16
