# Configuration file for LLVM IR Transformer
# Maps array references to capability indices


["%xC"]
"cap" = 0
"device" = "host"
"size" = 2

["%xorig"]
"cap" = 1
"device" = "host"
"size" = 16384

["%xsol"]
"cap" = 2
"device" = "host"
"size" = 16384

["%C"]
"cap" = 3
"device" = "local"
"size" = 2

["%orig"]
"cap" = 4
"device" = "local"
"size" = 16384

["%sol"]
"cap" = 5
"device" = "local"
"size" = 16384
