# Configuration file for LLVM IR Transformer
# Maps array references to capability indices

["%a"]
"cap" = 0
"device" = "host"
"size" = 10
#"accesses" = [ %2 ] # Only include accesses to check

["%b"]
"cap" = 1
"device" = "host"
"size" = 10

["%c"]
"cap" = 2
"device" = "host"
"size" = 10
#"accesses" = [("%mul", "%arrayidx4")] # When we do analysis pass, confirm if there can be multiple stores with same arguments. Add assert into python script to see if there's multiple matches? 



