# Configuration file for LLVM IR Transformer
# Maps array references to capability indices

["%xa"]
"cap" = 0
"device" = "host"
"size" = 2048
"omit_array" = true

["%xb"]
"cap" = 1
"device" = "host"
"size" = 2048
"omit_array" = true

["%xbucket"]
"cap" = 2
"device" = "host"
"size" = 2048
"omit_array" = true

["%xsum"]
"cap" = 3
"device" = "host"
"size" = 128
"omit_array" = true

["%a"]
"cap" = 4
"device" = "local"
"size" = 2048
"omit_array" = true

["%b"]
"cap" = 5
"device" = "local"
"size" = 2048
"omit_array" = true

["%bucket"]
"cap" = 6
"device" = "local"
"size" = 2048
"omit_array" = true

["%sum"]
"cap" = 7
"device" = "local"
"size" = 128
"omit_array" = true
