name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  software-regression-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: "true"

    # -----------
    # Fetch Cheri submodules   
    # -----------

    - uses: actions/checkout@v3
      with:
        repository: CTSRD-CHERI/cheribuild 
        path: ./cheri-tools/cheribuild
        submodules: "false" 

    - uses: actions/checkout@v3
      with:
        repository: CTSRD-CHERI/llvm-project 
        path: ./cheri-tools/llvm-project
        submodules: "false" 

    - uses: actions/checkout@v3
      with:
        repository: CTSRD-CHERI/gdb 
        path: ./cheri-tools/gdb
        submodules: "false" 

    - uses: actions/checkout@v3
      with:
        repository: CTSRD-CHERI/qemu 
        path: ./cheri-tools/qemu
        submodules: "false" 

    - uses: actions/checkout@v3
      with:
        repository: CTSRD-CHERI/cheribsd 
        path: ./cheri-tools/cheribsd
        submodules: "false" 

    # -----------
    # Build Cheri-HLS   
    # -----------
    
    - name: Get dependences 
      run: |
          sudo apt-get update
          sudo apt-get install apt-utils -y
          sudo apt-get install -y verilator gcc-riscv64-unknown-elf \
                                  libgmp-dev python3 python3-pip g++\
                                  clang llvm lld clang-tidy clang-format \
                                  gcc-multilib gcc cmake sudo wget vim \
                                  curl tmux git bc

          # Install CHERI dependencies
          sudo apt-get install -y autoconf automake libtool pkg-config \
                                  clang bison cmake mercurial ninja-build \
                                  samba flex texinfo time libglib2.0-dev \
                                  libpixman-1-dev libarchive-dev libarchive-tools \
                                  libbz2-dev libattr1-dev libcap-ng-dev \
                                  libexpat1-dev libgmp-dev

          pip3 install --user --upgrade pip
          pip3 install black colorlog toml tabulate 

    - name: Build Cheri 
      run: |
          make build

